# Generated by Django 5.0.6 on 2024-07-08 06:41

import blog.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to=blog.helpers.SaveMedia.save_image_path),
        ),
    ]
