# Generated by Django 5.0.6 on 2024-07-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_books_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='book',
            new_name='kitob',
        ),
        migrations.AlterField(
            model_name='auther',
            name='birth_day',
            field=models.DateField(verbose_name="TUG'ILGAN SANASI"),
        ),
        migrations.AlterField(
            model_name='auther',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="RUYHATDAN O'TGAN SANA"),
        ),
        migrations.AlterField(
            model_name='auther',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='ISM'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='FAMILIYA'),
        ),
    ]
